server:
  port: 8084
  servlet:
    context-path: '/ead-notification-hex/'

spring:
  application:
    name: ead-notification-service-hex

  datasource:
    url: jdbc:postgresql://localhost:5432/ead-notification-hex
    username: postgres
    password: Amarelo
  jpa:
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://dkcjxfat:a3hNKkm6M4knzO1lEgCwEEGckwl4eCmj@moose.rmq.cloudamqp.com/dkcjxfat

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health