server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser-v2
    username: postgres
    password: Amarelo
  jpa:
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://dkcjxfat:a3hNKkm6M4knzO1lEgCwEEGckwl4eCmj@moose.rmq.cloudamqp.com/dkcjxfat

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent


resilience4j:
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        .slidingWindowSize: 30
        .permittedNumberOfCallsInHalfOpenState: 2
        .slidingWindowType: TIME_BASED
        .minimumNumberOfCalls: 2
        .waitDurationInOpenState: 30s
        .failureRateThreshold: 80

